name: chitory_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  animated_splash_screen: ^1.3.0
  lottie: ^2.0.0
  introduction_slider: ^2.0.1
  introduction_screen: ^3.1.1
  google_fonts: ^3.0.1
  flutter_spinkit: ^5.1.0
  hexcolor: ^3.0.1
  icon: ^2.2.1
  flutter_signin_button: ^2.0.0
  otp_text_field: ^1.1.3
  font_awesome_flutter: ^9.1.0
  dependencies:
  get: ^4.6.1
  dropdownfield: ^1.0.3
  firebase_auth: ^4.1.5
  firebase_analytics: ^10.0.7
  cloud_firestore: ^4.1.0
  firebase_core: ^2.4.0
  firebase_database: ^10.0.7
  firebase_app_check: ^0.1.1+7
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  # image_path_android: "assets/image.png"
  image_path: "assets/Images/Light Mode Images/chitory-logo.jpg"
  android: true
  ios: true
  adaptive_icon_background: "ffffff"
  adaptive_icon_foreground: "assets/Images/Light Mode Images/chitory-logo.jpg"

flutter: 
  uses-material-design: true

  assets:
    - assets/animations/loading.gif
    - assets/animations/signup-successful.gif
    - assets/animations/login-successful.gif
    - assets/animations/successfully-green.gif
    - assets/animations/coming-soon.gif
    - assets/animations/Forgot Password/confusion.gif
    - assets/Images/Light Mode Images/splash screen/chitory-logo.jpg
    - assets/Images/Light Mode Images/onboarding screen/Frame 1.png
    - assets/Images/Light Mode Images/onboarding screen/Frame 2.png
    - assets/Images/Light Mode Images/onboarding screen/Frame 3.png
    - assets/images/Dark Mode Images/access code page/Frame 1.jpg
    - assets/Images/Light Mode Images/login page/background.jpg
    - assets/Images/Light Mode Images/login page/Frame 1.jpg
    - assets/Images/Light Mode Images/signup page/Frame 1.png
    - assets/Images/Light Mode Images/home page/Frame 1.png
    - assets/Images/Light Mode Images/home page/Frame 2.png
    - assets/Images/Light Mode Images/home page/Frame 3.png
    - assets/Images/Light Mode Images/dashboard/federal_poly_nasarawa/Frame 1.png
    - assets/Images/Light Mode Images/profile picture/Frame 1.png
    - assets/Images/Light Mode Images/profile picture/Frame 2.jpg
    - assets/Images/Light Mode Images/institutions/Frame 1.png
    - assets/Images/Light Mode Images/book image/Frame 1.png
    - assets/Images/Light Mode Images/answers to past questions/stb 122/2021n2022/image-diagram.jpg
 

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
