// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDzoiwMMUvl4GS672iscMtmMa8VcYcZC8',
    appId: '1:919902087604:web:10f21f446f9671b7956ae1',
    messagingSenderId: '919902087604',
    projectId: 'chitory-app',
    authDomain: 'chitory-app.firebaseapp.com',
    storageBucket: 'chitory-app.appspot.com',
    measurementId: 'G-S2RXEMHW4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP6-Ot_nGaM7tyQgp2QAHQJu6gR8q1I6I',
    appId: '1:919902087604:android:54921574aac47250956ae1',
    messagingSenderId: '919902087604',
    projectId: 'chitory-app',
    storageBucket: 'chitory-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpNI9yOlLIIqjLru5PD5lAixZztMHPEmE',
    appId: '1:919902087604:ios:a2601c34fd8ed400956ae1',
    messagingSenderId: '919902087604',
    projectId: 'chitory-app',
    storageBucket: 'chitory-app.appspot.com',
    iosClientId: '919902087604-09j9hgotidbfl04f8h04iodm3fc5tndt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpNI9yOlLIIqjLru5PD5lAixZztMHPEmE',
    appId: '1:919902087604:ios:a2601c34fd8ed400956ae1',
    messagingSenderId: '919902087604',
    projectId: 'chitory-app',
    storageBucket: 'chitory-app.appspot.com',
    iosClientId: '919902087604-09j9hgotidbfl04f8h04iodm3fc5tndt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitoryApp',
  );
}
